[package]
name = "demo-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.3"
tokio = { version = "1.27.0", features = ["macros"] }
ethers-gcp-kms-signer = { path = "../../" }
